### ISSUE TITLE
Keen.decryptScopedKey fails on keys encrypted by the Python client

### ISSUE THREAD

**Issue by JamiesonWarner** [keenlabs/KeenClient-Node#30]
The Keen clients in Python and Node have some incompatibilities. Try doing the following:

```python
# In Python:
from keen import scoped_keys
api_key = '80ce00d60d6443118017340c42d1cfaf'
my_scoped_key = scoped_keys.encrypt(api_key, { "foo": 12 })
print my_scoped_key
```

```javascript
// In Node:
var Keen = require('keen.io');
var apiKey = '80ce00d60d6443118017340c42d1cfaf';
Keen.decryptScopedKey(apiKey, my_scoped_key)
```

This results in:

```
TypeError: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at Decipheriv.Cipher.final (crypto.js:292:27)
    at Object.decryptScopedKey (/home/jamieson/Dropbox/Programming/Drifty/ionic-analytics-proxy/node_modules/keen.io/index.js:169:32)
    at repl:1:7
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
```

After a bit of digging, I noticed that different length plaintexts will cause this to either succeed or fail. For instance, if the plaintext is less than 16 bytes, this will always fail. I suspect this has to do with the different block sizes (for padding) used in the Python and Node libraries. The Python library [uses](https://github.com/keenlabs/KeenClient-Python/blob/master/keen/scoped_keys.py#L14) a 32 byte block size, whereas the Node crypto library (I think) uses a 16 byte block size. 

I'm definitely not a crypto expert, but any hints as to why this failing would be appreciated.

**Comment by dustinlarimer** [comment]
Closing here, if this issue is still a factor let's re-open in keen-js - thanks for all the input and good convo so far!
